version: '2.0'

services:
  server:
    build: .
    env_file:
      - .env
    environment:
      - PORT=8080
    ports:
      - 8080:8080
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: always
